language: c

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh github_package testthat
  
script: 
  - ./travis-tool.sh run_tests

after_script:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

    

